INSERT INTO MEMBER(EMAIL, PASSWORD, NAME, PHONE, GENDER) VALUES ('test1@test.co.kr', 'test1234', 'test1', '010-1234-1234', '1');
INSERT INTO MEMBER(EMAIL, PASSWORD, NAME, PHONE, GENDER) VALUES ('test2@test.co.kr', 'test1234', 'test2', '010-1234-1235', '1');

INSERT INTO PROFILE(MEMBER_ID, TITLE, CONTENT) VALUES(1L, 'title1', 'content1');
INSERT INTO PROFILE(MEMBER_ID, TITLE, CONTENT) VALUES(2L, 'title2', 'content2');
-- INSERT INTO PROFILE(MEMBER_ID, TITLE, CONTENT) VALUES(NULL, 'title2', 'content2');

INSERT INTO PICTURE(PROFILE_ID, PATH, NAME, SIZE, CREATE_DATE) VALUES(1L, 'path1', 'image1', 1024, NOW());
INSERT INTO PICTURE(PROFILE_ID, PATH, NAME, SIZE, CREATE_DATE) VALUES(1L, 'path2', 'image2', 1024, NOW());
INSERT INTO PICTURE(PROFILE_ID, PATH, NAME, SIZE, CREATE_DATE) VALUES(1L, 'path3', 'image3', 1024, NOW());
INSERT INTO PICTURE(PROFILE_ID, PATH, NAME, SIZE, CREATE_DATE) VALUES(2L, 'path1', 'image1', 1024, NOW());
INSERT INTO PICTURE(PROFILE_ID, PATH, NAME, SIZE, CREATE_DATE) VALUES(2L, 'path2', 'image2', 1024, NOW());
INSERT INTO PICTURE(PROFILE_ID, PATH, NAME, SIZE, CREATE_DATE) VALUES(2L, 'path3', 'image3', 1024, NOW());
